### ISSUE TITLE
CEASE AND DESIST

### ISSUE THREAD

**Issue by davidmashe** [newyork-anthonyng/Vicinity#1]
Dear Mr Ng,

On behalf of David Ashe III, we hereby order you to cease and desist the development of this application, which infringes upon the intellectual property of the forthcoming app HappyAt, the best way to find a happy hour(trademark filed). You are welcome to go build a daily cheer-ups app, or some shit.

jk, good luck on this, sounds awesome.

**Comment by newyork-anthonyng** [comment]
:+1:
